---
abstract: 'A Perl API for the Envolve web chat system.'
author:
  - 'JT Smith <RIZEN@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.102340, CPAN::Meta::Converter version 2.101670'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Chat-Envolve
no_index:
  directory:
    - author.t
    - eg
requires:
  Digest::HMAC_SHA1: 1.01
  Encode: 0
  MIME::Base64: 0
  Moose: 0.93
  Test::More: 0
resources:
  bugtracker: http://github.com/rizen/Chat-Envolve/issues
  repository: git://github.com/rizen/Chat-Envolve.git
version: 1.0002
